# .github/workflows/update_analysis_data.yml

name: Update Analysis Data and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # --- START: NEW, VERIFIED, AND SIMPLER VPN ACTION ---
      # This action connects to a free public VPN in Germany.
      # It downloads the configuration file directly, so no secrets are needed.
      - name: Setup VPN Connection
        uses: h3poteto/github-action-openvpn@v1.1.0
        with:
          config_file: .github/vpn/de1.vpnbook.com_tcp80.ovpn
          username: vpnbook
          password: ${{ secrets.VPN_PASSWORD }} # You will need to create this one secret

      # --- END: NEW VPN ACTION ---

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow scipy scikit-learn matplotlib mplfinance

      - name: Run Analysis and Charting Scripts
        run: |
          python generate_accurate_ma.py
          python sr_levels_analysis.py
          python generate_charts.py

      - name: Verify generated files
        run: ls -R

      # Use the official actions to build and deploy the site
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
