# .github/workflows/update_analysis_data.yml

name: Update Analysis Data and Deploy to Pages

on:
  push:
    branches: ["main"] # Run on every push to the main branch
  workflow_dispatch: # Allows manual runs

# Set permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, cancel older runs
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job 1: Build the site by running Python scripts
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests scipy scikit-learn matplotlib mplfinance beautifulsoup4 lxml

      - name: Run Analysis Scripts
        run: |
          python generate_accurate_ma.py
          python sr_levels_analysis.py

      - name: Generate Chart Images
        run: python generate_charts.py
      
      - name: Verify generated files for artifact
        run: ls -R

      # --- THIS IS THE CRITICAL "PACKAGING" STEP ---
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire repository content. This includes index.html, the generated
          # JSON files, and the charts folder.
          path: '.'

  # Job 2: Deploy the packaged site to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-data # This job will only run if the 'update-data' job succeeds
    steps:
      # --- THIS IS THE "DELIVERY" STEP ---
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
