# .github/workflows/main.yml

name: Update Accurate Analysis Data Files

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache and Restore Historical Data
        id: cache-ohlc
        uses: actions/cache@v4
        with:
          path: warmup_ohlc_data_fixed
          key: ${{ runner.os }}-ohlc-v2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ohlc-v2-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- CORRECTED STEP ---
      # Removed 'stefanzweifel/git-auto-commit-action' from the pip command
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow

      - name: Seed initial data if cache is empty
        if: steps.cache-ohlc.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cache not found. Seeding from release artifact..."
          # The GitHub CLI 'gh' is pre-installed on ubuntu-latest runners now
          # so we don't need to install it.
          gh release download v1.0-data -p "historical-data-v1.zip"
          unzip historical-data-v1.zip -d .
          echo "Seeding complete. The warmup_ohlc_data_fixed directory is now populated."
          ls -R warmup_ohlc_data_fixed

      - name: Run Python scripts to generate JSON
        run: |
          python generate_accurate_ma.py

      # This step uses the Action correctly and does NOT require a pip install
      - name: Commit and push ONLY JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data update"
          file_pattern: ma_analysis.json
