# .github/workflows/update_analysis_data.yml

name: Update Analysis Data and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # Needed for the git-auto-commit step
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- THIS IS THE FINAL, CORRECT INSTALLATION STEP ---
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          # Includes ALL libraries needed by ALL scripts:
          # - pandas, requests: Core libraries
          # - pyarrow: For the caching in generate_accurate_ma.py
          # - scipy, scikit-learn: For advanced S/R analysis
          # - matplotlib, mplfinance: For charting
          # - beautifulsoup4, lxml: For the original, more robust proxy scraping
          pip install pandas requests pyarrow scipy scikit-learn matplotlib mplfinance beautifulsoup4 lxml

      - name: Run Analysis and Charting Scripts
        run: |
          python generate_accurate_ma.py
          python sr_levels_analysis.py
          python generate_charts.py

      # This step is for debugging and can be removed later if desired
      - name: Verify generated files
        run: ls -R

      # Use the upload-pages-artifact action to prepare for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-data # This job runs only after the update-data job succeeds
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
