# .github/workflows/update_analysis_data.yml

name: Update Analysis Data via Local Script

on:
  schedule:
    - cron: '2-59/15 * * * *'
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # This is essential to allow the script to push back

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow scipy scikit-learn matplotlib mplfinance

      - name: Run the master update script
        run: |
          chmod +x run_update.sh
          ./run_update.sh
