name: Update Analysis Data Files

on:
  # Runs on a schedule every 15 minutes (at :00, :15, :30, :45 past the hour)
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    # Grant permissions for the GITHUB_TOKEN to be able to push to the repository.
    permissions:
      contents: write

    steps:
      # 1. Checks out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Runs your Python scripts to generate the JSON files
      - name: Run Python scripts to generate JSON
        run: |
          python sr_levels_analysis.py
          python ma_analysis.py

      # 5. Use a dedicated action to commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data update"
          file_pattern: sr_levels_analysis.json ma_analysis.json
