# .github/workflows/main.yml

name: Update Accurate Analysis Data Files

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Add permission for actions to read/write artifacts
      actions: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- START OF ARTIFACT LOGIC ---
      - name: Download latest cache artifact
        # This action finds the latest artifact from this workflow on this branch
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ohlc-cache
          path: warmup_ohlc_data_fixed
          # This is not an error if it's the first run, so we ignore failure
          if_no_artifact_found: ignore
      # --- END OF ARTIFACT LOGIC ---

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python scripts to generate JSON
        run: |
          python sr_levels_analysis.py
          python generate_accurate_ma.py

      # --- START OF UPDATED ARTIFACT LOGIC ---
      - name: Upload updated cache for next run
        # This action uploads the folder as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ohlc-cache
          path: warmup_ohlc_data_fixed/
          retention-days: 7 # Keep the cache artifact for a week
      # --- END OF UPDATED ARTIFACT LOGIC ---

      - name: Commit and push ONLY JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data update"
          # We ONLY commit the small JSON files to the repository
          file_pattern: sr_levels_analysis.json ma_analysis.json
