# .github/workflows/update_analysis_data.yml

name: Update Analysis Data and Charts

on:
  schedule:
    - cron: '2-59/15 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow scipy scikit-learn matplotlib mplfinance

      - name: Run Analysis Scripts
        run: |
          python generate_accurate_ma.py
          python sr_levels_analysis.py

      - name: Generate Chart Images
        run: python generate_charts.py

      # --- START: CHANGE 1 (FOR DEBUGGING) ---
      - name: Verify generated files
        run: |
          echo "Verifying contents of the workspace..."
          ls -R
      # --- END: CHANGE 1 ---

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      # --- START: CHANGE 2 (THE FIX) ---
      - name: Commit and push all changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data and chart update"
          # By REMOVING the 'file_pattern' line, this action will automatically
          # commit ALL new and modified files. This is more robust and won't
          # fail if the charts aren't generated for some reason.
      # --- END: CHANGE 2 ---
