# .github/workflows/main.yml

name: Update Accurate Analysis Data Files

on:
  schedule:
    - cron: '2-59/15 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache and Restore Historical Data
        id: cache-ohlc
        uses: actions/cache@v4
        with:
          path: warmup_ohlc_data_fixed
          key: ${{ runner.os }}-ohlc-v2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ohlc-v2-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # <-- THIS IS THE FIX: Added scipy and scikit-learn for the second script
          pip install pandas requests pyarrow scipy scikit-learn

      - name: Seed initial data if cache is empty
        if: steps.cache-ohlc.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cache not found. Seeding from release artifact..."
          gh release download v1.0-data -p "warmup_ohlc_data_fixed.zip"
          unzip -o warmup_ohlc_data_fixed.zip -d .
          echo "Seeding complete. The warmup_ohlc_data_fixed directory is now populated."
          ls -R warmup_ohlc_data_fixed

      - name: Run Python scripts to generate JSON
        run: |
          python generate_accurate_ma.py
          python sr_levels_analysis.py

      - name: Commit and push ONLY JSON files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated analysis data update"
          file_pattern: ma_analysis.json sr_levels_analysis.json
